### PR TITLE
Changes to honor fixed and initial x and y postions.

### PR DESCRIPTION
**Pull request by srobertson**
The particle system isn't pushing enough information to the background worker. More could be done.

### CODE REVIEW

**Comment by JeffAMcGee** [comment]
I'm dealing with this same bug at the moment. I actually wrote a similar patch, and was about to fork arbor and post it, but then I saw this.

There is a small problem with the patch you supplied: If you create a point with the position (0,0), it goes to a random location, instead of the origin. Something like this will work:
c.p.x===null ? c.p.x: _bounds.topleft.x + w*Math.random(),

**Comment by srobertson** [comment]
Good catch Jeff, thanks.

**Comment by samizdatco** [comment]
Thanks for noticing this (and for the fix). I've updated the code to something similar to what's here but stuck to the behavior listed in the docs for specifying the initial position (i.e., using `{x:, y:, fixed:}` rather than `{p:{x:,y:}, fixed:}` in the `.addNode` args).

**Comment by gruppler** [comment]
If I specify initial x and y values for nodes when I create them, nothing moves. It looks like the renderer's init function is never called.

**Pull request closed without merging**
